version: '3.7'
services:
  nginx:
    image: nginx:1.16
    ports:
      - 80:80
    volumes:
      - .:/usr/src/php-skeleton
      - ./configuration/docker/site.txt:/etc/nginx/conf.d/default.conf
  php:
    image: php:7.4-fpm
    volumes:
      - .:/usr/src/php-skeleton
  mariadb:
    image: mariadb:10.4
    ports:
      - 3307:3306
    volumes:
      - ./tmp/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: php_skeleton
      MYSQL_USER: php_skeleton
      MYSQL_PASSWORD: php_skeleton
