---
apiVersion: apps/v1
kind: Deployment
metadata:
  # This used to be php-skeleton-deployment to be better distinguishable, but a suffix of the kind that it is seems redundant.
  name: php-skeleton
  labels:
    app: php-skeleton-label
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-skeleton-label
  template:
    metadata:
      labels:
        app: php-skeleton-label
    spec:
      containers:
      - name: php-skeleton
        image: '{{ .Values.ImagePrefix }}/php-skeleton:{{ .Chart.AppVersion }}'
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: regcred
