---
apiVersion: v1
kind: Service
metadata:
  # This used to be php-skeleton-service to be better distinguishable, but a suffix of the kind that it is seems redundant. It also determines the cluster domain.
  name: php-skeleton
spec:
  selector:
    app: php-skeleton-label
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
